name: CI/CD for React

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build

      # Example deploy step (for server via SCP)
      # - name: Deploy to Windows IIS
      #   run: |
      #     echo "Deploying to server..."
      #     scp -r build/* user@your-server:/var/www/html
